PREFIX dbpedia: <http://dbpedia.org/resource/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT ?title ?creator
FROM <http://www.homepages.ed.ac.uk/amanatak/medinf/book.ttl>
WHERE { 
      dbpedia:Logicomix dc:title ?title .
      dbpedia:Logicomix dc:creator ?creator .
      }